# score_outputs.py
"""Score LLM recommendations against the rule‑based ground truth.

The script expects a CSV of ground‑truth recommendations generated by
`src/baseline.py` (``ground_truth.csv``) and the output CSVs produced by
``run_experiments.py`` (``results/<prompt>_outputs.csv``).

For each prompt we compute a simple *hit‑rate*: a recommendation is considered
correct if the recommended ``card_id`` matches the ground‑truth ``card_id``.
The results are written to ``results/<prompt>_score.json``.
"""

import json
from pathlib import Path
import pandas as pd

GROUND_TRUTH = Path(__file__).parents[1] / "data" / "ground_truth.csv"
RESULTS_DIR = Path(__file__).parents[1] / "results"
PROMPT_NAMES = ["zero_shot", "structured", "few_shot"]


def load_ground_truth() -> pd.DataFrame:
    return pd.read_csv(GROUND_TRUTH)


def normalise_recommendation(text: str) -> str:
    """Extract a credit‑card identifier from free‑form LLM output.

    The LLM may return the card name, ID or a description.  We attempt to map
    it to the ``card_id`` column of ``cards.csv`` by a case‑insensitive search.
    """
    # Very simple heuristic – look for a token that matches the pattern CC\d{3}
    import re
    match = re.search(r"CC\d{3}", text, re.IGNORECASE)
    if match:
        return match.group(0).upper()
    # Fallback: return stripped lower‑cased text for direct comparison
    return text.strip().lower()


def score_prompt(prompt: str, gt: pd.DataFrame) -> dict:
    out_path = RESULTS_DIR / f"{prompt}_outputs.csv"
    if not out_path.is_file():
        return {"error": f"Missing {out_path.name}"}
    df = pd.read_csv(out_path)
    # Normalise both sides
    gt_map = dict(zip(gt["profile_id"], gt["card_id"]))
    hits = 0
    total = len(df)
    for _, row in df.iterrows():
        pid = row["profile_id"]
        pred = normalise_recommendation(row["recommendation"])
        true = gt_map.get(pid)
        if true and pred == true:
            hits += 1
    accuracy = hits / total if total else 0.0
    return {"prompt": prompt, "accuracy": accuracy, "total": total, "hits": hits}


def main():
    gt = load_ground_truth()
    summary = {}
    for prompt in PROMPT_NAMES:
        summary[prompt] = score_prompt(prompt, gt)
        # Persist per‑prompt JSON
        json_path = RESULTS_DIR / f"{prompt}_score.json"
        with open(json_path, "w", encoding="utf-8") as jf:
            json.dump(summary[prompt], jf, indent=2)
        print(f"✅ {prompt} – {summary[prompt]['accuracy']:.2%} accuracy (" 
              f"{summary[prompt]['hits']}/{summary[prompt]['total']})")
    # Overall summary file
    with open(RESULTS_DIR / "score_summary.json", "w", encoding="utf-8") as sf:
        json.dump(summary, sf, indent=2)
    print("🗒️ Detailed scores saved in results/ directory")


if __name__ == "__main__":
    main()
